export const SET_CURRENT_PRODUCT_REVIEWS_PAGE_DATA = 'SET_CURRENT_PRODUCT_REVIEWS_PAGE_DATA'
export const SET_CURRENT_PRODUCT_REVIEWS = 'SET_CURRENT_PRODUCT_REVIEWS'
export const ADD_MORE_PRODUCT_REVIEWS = 'ADD_MORE_PRODUCT_REVIEWS'
export const SET_PRODUCT_RATING = 'SET_PRODUCT_RATING'